### ISSUE TITLE
HFP data normalization

### ISSUE THREAD

**Issue by Divinare** [HSLdevcom/hfp-analytics#11]
* Normalize data with splitting observation into two tables: observation_journey & observation_event
  * observation_journey columns: journey_id (primary key), direction, journey_start_time, oday, route_id
  * observation_event columns: journey_id (foreign key, references observation_journey), tst (rounded to the nearest second), events (a list of multiple event types VP, DOC, DOO), ...
     * multiple events are combined here if they belong to the same second
  * update /hfp_points/{stop_id} to return observation_event rows instead of observation rows

**Comment by datarttu** [comment]
Resolved by #13 .
