### ISSUE TITLE
Save logs to db

### ISSUE THREAD

**Issue by Divinare** [HSLdevcom/hfp-analytics#9]
Create a new table with two columns: timestamp, logs?

Which logs to save? At least if import or run analysis have failed.

**Comment by teemu8655** [comment]
Import fails + analysis fails to logs

**Comment by datarttu** [comment]
Some ideas related to logging:

- Use Python's [logging](https://docs.python.org/3/library/logging.html) library just like you'd do with `print()`, but apply logging levels (debug, info, warning, error, critical) as well
- Different loggers can be configured:
  - for local development / debugging -> printing to stdout -> configure such that this is not used in production / Azure
  - for saving important log entries to db -> used only in production / Azure, logging level > INFO or WARNING
- See [this article](https://medium.com/nerd-for-tech/logging-with-logging-in-python-d3d8eb9a155a) for how a logging handler for SQL db can be configured (example 3). I think a similar approach for Postgres is easy to create too.
- Save db logs to a separate schema, e.g. `CREATE SCHEMA logs;` and push Python logs e.g. to `logs.api_log` table.
  - This schema can then be used for other logging-related tables too, e.g. if we want to save logs from within the database, not just from Python.
  - Don't worry too much about the log table structure - just a serial pkey column, timestamp, and text contents will do, I think: `CREATE TABLE logs.api_log (rowid bigserial PRIMARY KEY, log_timestamp timestamptz DEFAULT now(), log_text text)` -> Python logger can just throw stuff into `logs.api_log (log_text)`, other columns are populated automatically.
- By logging stuff to the db we can accumulate useful information for later analysis: for point-in-time queries ("what happened with this specific import") or broader analyses such as grepping particular occurrences over a longer time ("were there failed imports during week X -> what happened with them?").
  - Wise use of logging levels helps with this: e.g. use INFO for anything "normal" (e.g. this many rows were inserted now), WARNING for anything that we know should be "unusual" (e.g. > 0 rows found where tst / operator_id / vehicle_number was missing and row could therefore not be inserted), ERROR for anything that breaks something (e.g. an entire import failed).
